
name: Build and deploy container app to Azure Web App - api-travel-ways

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: "ubuntu-latest"

        steps:
            - uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to registry
              uses: docker/login-action@v1
              with:
                  registry: https://tavelways.azurecr.io/
                  username: ${{ secrets.AzureAppService_ContainerUsername_8957bc4e2476498482ab5c63929dce16 }}
                  password: ${{ secrets.AzureAppService_ContainerPassword_8d5c6fe295284a3192fe3fe3a95de20a }}

            - name: Build and push container image to registry
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: tavelways.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8957bc4e2476498482ab5c63929dce16 }}/travel-ways-api:${{ github.sha }}
                  file: ./Dockerfile
                  build-args: |
                      CONNECTION_STRING=${{secrets.CONNECTION_STRING}}
                      DB_PASSWORD=${{secrets.DB_PASSWORD}}
                      DB_USER=${{secrets.DB_USER}}
                      MAIL_PASSWORD=${{secrets.MAIL_PASSWORD}}

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "api-travel-ways"
                  slot-name: "production"
                  publish-profile: ${{ secrets.AzureAppService_PublishProfile_75b6fe5a6e434ce2abd6ab5ad642271c }}
                  images: "tavelways.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8957bc4e2476498482ab5c63929dce16 }}/travel-ways-api:${{ github.sha }}"
